### ISSUE TITLE
Rust side support

### ISSUE THREAD

**Issue by nwrenger** [lindongchen/tauri-plugin-share#2]
Hey, I was wondering if it would be possible to use the library from the rust side. For example, the official dialog plugin has a rust API:
```rust
use tauri_plugin_dialog::{DialogExt, MessageDialogButtons};

let answer = app.dialog()
        .message("Tauri is Awesome")
        .title("Tauri is Awesome")
        .buttons(MessageDialogButtons::OkCancelCustom("Absolutely", "Totally"))
        .blocking_show();
```

**Comment by lindongchen** [comment]
you can try it
```
use tauri_plugin_share::{ShareExt,ShareResponse};
app.share().share_file(...
```
impl should be compared with https://github.com/lindongchen/tauri-plugin-share/blob/main/src/lib.rs
but as I know, the dialog plugin also has an npm lib...

**Comment by nwrenger** [comment]
Ah, I see. But it seems you've made a small error here. The `share` method doesn't exist on the `ShareExt` trait. The impls `share_file`, `get_shared_files` and `get_shared_files_path` all exists but are doing the same and should be put into one function, a `share` function. Even when accessing the state via one of those functions, like this:
```rust
use tauri_plugin_share::{ShareExt, ShareRequest};
app.share_file().share_file(ShareRequest {
    path: Some(String::new()),
    mime: Some(String::new()),
    group: None,
})?;
```
It won't trigger any opening of a share dialog (tested on an iPhone). Despite this, the triggering on the frontend using the `npm` package or an `invoke` works.
